// Code generated by togo. DO NOT EDIT.

package i18n

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"golang.org/x/text/language"
)

// list of embedded template files.
var files = []struct {
	name string
	data string
}{
	{
		name: "active.en-US.json",
		data: activeenUS,
	}, {
		name: "active.es-ES.json",
		data: activeesES,
	}, {
		name: "active.fr-FR.json",
		data: activefrFR,
	}, {
		name: "active.zh-CN.json",
		data: activezhCN,
	}, {
		name: "translate.zh-CN.json",
		data: translatezhCN,
	},
}

var I18n = i18n.NewBundle(language.English)

func init() {
	for _, file := range files {
		I18n.ParseMessageFileBytes([]byte(file.data), file.name)
	}
}

//
// embedded template files.
//

// files/active.en-US.json
var activeenUS = `{
  "greeting": "Hello",
  "welcome": "Welcome"
}
`

// files/active.es-ES.json
var activeesES = `{
  "greeting": {
    "hash": "sha1-f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0",
    "other": "Hola"
  },
  "welcome": {
    "hash": "sha1-ca4f9dcf204e2037bfe5884867bead98bd9cbaf8",
    "other": "Bienvenidos"
  }
}
`

// files/active.fr-FR.json
var activefrFR = `{
  "greeting": {
    "hash": "sha1-f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0",
    "other": "Bonjour"
  },
  "welcome": {
    "hash": "sha1-ca4f9dcf204e2037bfe5884867bead98bd9cbaf8",
    "other": "Bienvenue"
  }
}
`

// files/active.zh-CN.json
var activezhCN = `{}
`

// files/translate.zh-CN.json
var translatezhCN = `{
  "greeting": {
    "hash": "sha1-f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0",
    "other": "Hello"
  },
  "welcome": {
    "hash": "sha1-ca4f9dcf204e2037bfe5884867bead98bd9cbaf8",
    "other": "Welcome"
  }
}
`
